#ifndef RVV_MDF_OPT_CONFIG_H
#define RVV_MDF_OPT_CONFIG_H

#define OVERRIDE_MDF_INNER_PROD
#define OVERRIDE_MDF_POWER_SPECTRUM

#define OVERRIDE_MDF_POWER_SPECTRUM_ACCUM
#define OVERRIDE_MDF_SPECTRAL_MUL_ACCUM
#define OVERRIDE_MDF_SPECTRAL_MUL_ACCUM16
#define OVERRIDE_MDF_WEIGHT_SPECT_MUL_CONJ
#define OVERRIDE_MDF_ADJUST_PROP
#define OVERRIDE_MDF_PREEMPH_FLT
#define OVERRIDE_MDF_STRIDED_PREEMPH_FLT


#define OVERRIDE_MDF_VEC_SUB
#define OVERRIDE_MDF_VEC_SUB_INT16

#define OVERRIDE_MDF_VEC_ADD
#define OVERRIDE_MDF_VEC_MULT
#define OVERRIDE_MDF_VEC_SCALE
#define OVERRIDE_MDF_SMOOTHED_ADD
#define OVERRIDE_MDF_SMOOTH_FE_NRG
#define OVERRIDE_MDF_FILTERED_SPEC_AD_XCORR

#define OVERRIDE_MDF_NORM_LEARN_RATE_CALC

#define OVERRIDE_MDF_CONVERG_LEARN_RATE_CALC

/*
*/

#endif /* RVV_MDF_OPT_CONFIG_H */
